import type { Metadata } from 'next';
import '../.././globals.css';
import Navbar from '../_components/Navbar/Navbar';
import Footer from '../_components/Footer/Footer';
import { fahkwang, dmSans } from '../_fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fahkwang.variable} ${dmSans.variable} bg-black`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
